services:
  postgres-hotel:
      container_name: postgres-hotel
      image: postgres:latest
      environment:
        POSTGRES_DB: hotel_service_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        PGDATA: /data/postgres
      volumes:
        - ./postgres-hotel:/data/postgres
      ports:
        - '5431:5432'
      expose:
        - '5432'
      restart: always

  postgres-vol:
     container_name: postgres-vol
     image: postgres:latest
     environment:
       POSTGRES_DB: vol_service_db
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       PGDATA: /data/postgres
     volumes:
       - ./postgres-vol:/data/postgres
     ports:
       - '5432:5432'
     expose:
       - '5432'
     restart: always

  postgres-payment:
    container_name: postgres-payment
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-payment:/data/postgres
    ports:
      - '5433:5432'
    expose:
      - '5432'
    restart: always

  postgres-reservation:
    container_name: postgres-reservation
    image: postgres:latest
    environment:
     POSTGRES_DB: reservation_service_db
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password
     PGDATA: /data/postgres
    volumes:
      - ./postgres-reservation:/data/postgres
    ports:
      - '5434:5432'
    expose:
      - '5432'
    restart: always

  mongo-card:
    image: mongo:latest
    container_name: mongo-card
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    restart: always
    

  discovery-service:
    image: travelsystem/discovery-service:latest
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  config-service:
    image: travelsystem/config-service:latest
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    env_file:
      - variables.env
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      discovery-service:
        condition: service_healthy

  gateway-service:
     image: travelsystem/gateway-service:latest
     container_name: gateway-service
     ports:
       - '8888:8888'
     expose:
       - '8888'
     environment:
       - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
       - CONFIG_SERVICE_URL=http://config-service:9999
       - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
     depends_on:
       config-service:
         condition: service_healthy
       zipkin:
         condition: service_started

  hotel-service:
    image: travelsystem/hotel-service:latest
    container_name: hotel-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
       - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
       - CONFIG_SERVICE_URL=http://config-service:9999
       - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
       - HOTEL_DB=jdbc:postgresql://postgres-hotel:5432
    depends_on:
      config-service:
        condition: service_healthy
      postgres-hotel:
        condition: service_started
      zipkin:
        condition: service_started

  vol-service:
    image: travelsystem/vol-service:latest
    container_name: vol-service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - VOL_DB=jdbc:postgresql://postgres-vol:5432
    depends_on:
      config-service:
        condition: service_healthy
      postgres-vol:
        condition: service_started
      zipkin:
        condition: service_started

  reservation-service:
    image: travelsystem/reservation-service:latest
    container_name: reservation-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - RESERVATION_DB=jdbc:postgresql://postgres-reservation:5432
      - KAFKA_URL=http://broker:9092
    env_file:
      - variables.env
    depends_on:
      config-service:
        condition: service_healthy
      postgres-reservation:
        condition: service_started
      broker:
        condition: service_started
      zipkin:
        condition: service_started

  payment-service:
    image: travelsystem/payment-service:latest
    container_name: payment-service
    ports:
      - '8087:8087'
    expose:
      - '8087'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - KAFKA_URL=http://broker:9092
      - CARD_SERVICE_URL=http://card-service:9090
      - PAYMENT_DB=jdbc:postgresql://postgres-payment:5432
    depends_on:
      config-service:
        condition: service_healthy
      postgres-payment:
        condition: service_started
      broker:
        condition: service_started
      zipkin:
        condition: service_started

  card-service:
    image: travelsystem/card-server:latest
    container_name: card-service
    ports:
      - '9090:9090'
    expose:
      - '9090'
    environment:
      - KAFKA_URL=http://broker:9092
      - CARD_DB=mongodb://mongo-card:27017
    depends_on:
      config-service:
        condition: service_healthy
      mongo-card:
        condition: service_started
      broker:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"