services:
  postgres-hotel:
      container_name: postgres-hotel
      image: postgres:latest
      environment:
        POSTGRES_DB: hotel_service_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - postgres-hotel-data:/var/lib/postgresql/data
      ports:
        - '5431:5432'
      expose:
        - '5432'
      restart: always

  postgres-vol:
     container_name: postgres-vol
     image: postgres:latest
     environment:
       POSTGRES_DB: vol_service_db
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
     volumes:
       - postgres-vol-data:/var/lib/postgresql/data
     ports:
       - '5438:5432'
     expose:
       - '5432'
     restart: always

  postgres-payment:
    container_name: postgres-payment
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    expose:
      - '5432'
    restart: always

  postgres-reservation:
    container_name: postgres-reservation
    image: postgres:latest
    environment:
     POSTGRES_DB: reservation_service_db
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password
    volumes:
      - postgres-reservation-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    expose:
      - '5432'
    restart: always

  mongo-card:
    image: mongo:latest
    container_name: mongo-card
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-card-data:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    restart: always

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:latest
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
      - '8085:8085'
      - '8087:8087'

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    network_mode: "service:localhost"
    depends_on:
      keycloak-postgres:
        condition: service_started

  discovery-service:
    image: travelsystem/discovery-service:latest
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'

  config-service:
    image: travelsystem/config-service:latest
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    env_file:
      - variables.env
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_started

  gateway-service:
     image: travelsystem/gateway-service:latest
     container_name: gateway-service
     ports:
       - '8888:8888'
     expose:
       - '8888'
     environment:
       - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
       - CONFIG_SERVICE_URL=http://config-service:9999
       - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
     depends_on:
       config-service:
         condition: service_started
       zipkin:
         condition: service_started

  hotel-service:
    image: travelsystem/hotel-service:latest
    container_name: hotel-service
    network_mode: "service:localhost"
    environment:
       - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
       - CONFIG_SERVICE_URL=http://config-service:9999
       - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
       - KEYCLOAK_URL=http://localhost:8080/realms/travel-system
       - KEYCLOAK_CERTS_URL=http://localhost:8080/realms/travel-system/protocol/openid-connect/certs
       - HOTEL_DB=jdbc:postgresql://postgres-hotel:5432/hotel_service_db
       - DB_USER=user
       - DB_PWD=password
    depends_on:
      config-service:
        condition: service_started
      postgres-hotel:
        condition: service_started
      zipkin:
        condition: service_started

  vol-service:
    image: travelsystem/vol-service:latest
    container_name: vol-service
    network_mode: "service:localhost"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - KEYCLOAK_URL=http://localhost:8080/realms/travel-system
      - KEYCLOAK_CERTS_URL=http://localhost:8080/realms/travel-system/protocol/openid-connect/certs
      - VOL_DB=jdbc:postgresql://postgres-vol:5432/vol_service_db
      - DB_USER=user
      - DB_PWD=password
    depends_on:
      config-service:
        condition: service_started
      postgres-vol:
        condition: service_started
      zipkin:
        condition: service_started

  reservation-service:
    image: travelsystem/reservation-service:latest
    container_name: reservation-service
    network_mode: "service:localhost"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - KEYCLOAK_URL=http://localhost:8080/realms/travel-system
      - KEYCLOAK_CERTS_URL=http://localhost:8080/realms/travel-system/protocol/openid-connect/certs
      - RESERVATION_DB=jdbc:postgresql://postgres-reservation:5432/reservation_service_db
      - DB_USER=user
      - DB_PWD=password
      - KAFKA_URL=broker:29092
      - FILE_UPLOAD_DIR=/app/Pictures
    volumes:
      - C:/Users/Administrator/Pictures:/app/Pictures
    env_file:
      - variables.env
    depends_on:
      config-service:
        condition: service_started
      postgres-reservation:
        condition: service_started
      broker:
        condition: service_started
      zipkin:
        condition: service_started

  payment-service:
    image: travelsystem/payment-service:latest
    container_name: payment-service
    network_mode: "service:localhost"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - KEYCLOAK_URL=http://localhost:8080/realms/travel-system
      - KEYCLOAK_CERTS_URL=http://localhost:8080/realms/travel-system/protocol/openid-connect/certs
      - KAFKA_URL=broker:29092
      - CARD_SERVICE_URL=http://card-service:9090/api/cards
      - PAYMENT_DB=jdbc:postgresql://postgres-payment:5432/payment_service_db
      - DB_USER=user
      - DB_PWD=password
    depends_on:
      config-service:
        condition: service_started
      postgres-payment:
        condition: service_started
      broker:
        condition: service_started
      zipkin:
        condition: service_started

  card-service:
    image: travelsystem/card-server:latest
    container_name: card-service
    ports:
      - '9090:9090'
    expose:
      - '9090'
    environment:
      - KAFKA_URL=broker:29092
      - CARD_DB=mongodb://admin:password@mongo-card:27017/card_service?authSource=admin
    depends_on:
      mongo-card:
        condition: service_started
      broker:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"

volumes:
  postgres-reservation-data:
  postgres-hotel-data:
  postgres-vol-data:
  postgres-payment-data:
  mongo-card-data:
  postgres-keycloak-data:
